### ISSUE TITLE
Webhook for katacoda

### ISSUE THREAD

**Issue by iranzo** [kubevirt/katacoda-scenarios#3]
Define a webhook in the repository settings using the payload defined at https://katacoda.com/kubevirt/settings 

With target url: https://editor.katacoda.com/scenarios/updated

and payload as application/json for 'send events'

**Comment by codificat** [comment]
@iranzo I added the hook.

I wasn't sure about what you meant with "for 'send events'"...  the choices we have when configuring when to trigger the webhook are:

  - just for the push event
  - send me everything
  - let me select individual events

I believe that we only need to check for updates so I selected "just the push event". If that's not what was needed let me know, otherwise feel free to close this as done.

**Comment by iranzo** [comment]
Perfect, thanks

/close
